In [1]:
import pandas as pd

In [2]:
dwell_loc = pd.read_csv("../data/loc_code_detection_patterns.csv")

In [3]:
direction = dwell_loc[['tag_id', 'loc_code', 'start_time', 'end_time', 'number_of_detections', 'dwell_time']]
direction = direction[direction['loc_code']!='3M'].replace('60','61') # remove 3M, 60 and 61 are the same-so replace
direction

,tag_id,loc_code,start_time,end_time,number_of_detections,dwell_time
0,989.001026,202,2018-05-30 12:44:10.620000,2018-05-30 12:44:10.620000,1,0 days 00:00:00
1,989.001026,202,2018-05-30 13:11:46.610000,2018-05-30 13:11:46.610000,1,0 days 00:00:00
2,989.001026,201,2018-05-30 15:10:44.680000,2018-05-30 15:10:46.230000,2,0 days 00:00:01.550000
3,989.001026,202,2018-05-30 15:11:52,2018-05-30 15:11:52,1,0 days 00:00:00
4,989.001026,202,2018-05-30 21:19:02.240000,2018-05-30 21:19:02.240000,1,0 days 00:00:00
...,...,...,...,...,...,...
231272,989.002028,51,2025-03-09 13:39:35.920000,2025-03-09 13:40:40.040000,2,0 days 00:01:04.120000
231273,989.002028,302,2025-03-10 06:39:50.720000,2025-03-10 06:39:50.720000,1,0 days 00:00:00
231274,989.002027,6A,2025-03-12 00:58:17.600000,2025-03-12 00:58:17.600000,1,0 days 00:00:00
231275,989.002027,6B,2025-03-12 01:00:24.080000,2025-03-12 01:00:24.080000,1,0 days 00:00:00
231276,989.002027,61,2025-03-12 05:11:39.740000,2025-03-12 05:11:39.740000,1,0 days 00:00:00

Testing the workflow for a single tag

In [4]:
ind = direction[direction['tag_id'] == 989.001038869832]
ind

,tag_id,loc_code,start_time,end_time,number_of_detections,dwell_time
6169,989.001039,84,2021-04-29 13:13:27.770000,2021-04-29 13:13:27.770000,1,0 days 00:00:00
6192,989.001039,83,2021-04-29 14:02:14.730000,2021-04-29 14:02:14.730000,1,0 days 00:00:00
6210,989.001039,84,2021-04-29 14:27:06.900000,2021-04-29 19:16:29.670000,4,0 days 04:49:22.770000
6306,989.001039,83,2021-04-29 19:33:12.160000,2021-04-29 19:34:53.880000,2,0 days 00:01:41.720000
6315,989.001039,84,2021-04-29 19:43:05,2021-04-29 20:16:52.380000,2,0 days 00:33:47.380000
24823,989.001039,83,2021-09-30 07:31:40.930000,2021-09-30 07:31:40.930000,1,0 days 00:00:00
24825,989.001039,84,2021-09-30 07:35:06.370000,2021-09-30 07:35:06.370000,1,0 days 00:00:00

In [5]:
ind["start_shift"] = ind["start_time"].shift(-1) 
ind

C:\Users\hp\AppData\Local\Temp\ipykernel_12276\310816678.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ind["start_shift"] = ind["start_time"].shift(-1)

,tag_id,loc_code,start_time,end_time,number_of_detections,dwell_time,start_shift
6169,989.001039,84,2021-04-29 13:13:27.770000,2021-04-29 13:13:27.770000,1,0 days 00:00:00,2021-04-29 14:02:14.730000
6192,989.001039,83,2021-04-29 14:02:14.730000,2021-04-29 14:02:14.730000,1,0 days 00:00:00,2021-04-29 14:27:06.900000
6210,989.001039,84,2021-04-29 14:27:06.900000,2021-04-29 19:16:29.670000,4,0 days 04:49:22.770000,2021-04-29 19:33:12.160000
6306,989.001039,83,2021-04-29 19:33:12.160000,2021-04-29 19:34:53.880000,2,0 days 00:01:41.720000,2021-04-29 19:43:05
6315,989.001039,84,2021-04-29 19:43:05,2021-04-29 20:16:52.380000,2,0 days 00:33:47.380000,2021-09-30 07:31:40.930000
24823,989.001039,83,2021-09-30 07:31:40.930000,2021-09-30 07:31:40.930000,1,0 days 00:00:00,2021-09-30 07:35:06.370000
24825,989.001039,84,2021-09-30 07:35:06.370000,2021-09-30 07:35:06.370000,1,0 days 00:00:00,None

In [6]:
ind["start_time"] = pd.to_datetime(ind["start_time"], format="ISO8601", errors="coerce")
ind["end_time"] = pd.to_datetime(ind["end_time"], format="ISO8601", errors="coerce")
ind["start_shift"] = pd.to_datetime(ind["start_shift"], format="ISO8601", errors="coerce")  # Convert 'NaT' to proper datetime NaT

ind["time_between_detection"] = ind["start_shift"] - ind["end_time"]

ind

C:\Users\hp\AppData\Local\Temp\ipykernel_12276\440862486.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ind["start_time"] = pd.to_datetime(ind["start_time"], format="ISO8601", errors="coerce")
C:\Users\hp\AppData\Local\Temp\ipykernel_12276\440862486.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ind["end_time"] = pd.to_datetime(ind["end_time"], format="ISO8601", errors="coerce")
C:\Users\hp\AppData\Local\Temp\ipykernel_12276\440862486.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ind["start_shift"] = pd.to_datetime(ind["start_shift"], format="ISO8601", errors="coerce")  # Convert 'NaT' to proper datetime NaT
C:\Users\hp\AppData\Local\Temp\ipykernel_12276\440862486.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ind["time_between_detection"] = ind["start_shift"] - ind["end_time"]

,tag_id,loc_code,start_time,end_time,number_of_detections,dwell_time,start_shift,time_between_detection
6169,989.001039,84,2021-04-29 13:13:27.770,2021-04-29 13:13:27.770,1,0 days 00:00:00,2021-04-29 14:02:14.730,0 days 00:48:46.960000
6192,989.001039,83,2021-04-29 14:02:14.730,2021-04-29 14:02:14.730,1,0 days 00:00:00,2021-04-29 14:27:06.900,0 days 00:24:52.170000
6210,989.001039,84,2021-04-29 14:27:06.900,2021-04-29 19:16:29.670,4,0 days 04:49:22.770000,2021-04-29 19:33:12.160,0 days 00:16:42.490000
6306,989.001039,83,2021-04-29 19:33:12.160,2021-04-29 19:34:53.880,2,0 days 00:01:41.720000,2021-04-29 19:43:05.000,0 days 00:08:11.120000
6315,989.001039,84,2021-04-29 19:43:05.000,2021-04-29 20:16:52.380,2,0 days 00:33:47.380000,2021-09-30 07:31:40.930,153 days 11:14:48.550000
24823,989.001039,83,2021-09-30 07:31:40.930,2021-09-30 07:31:40.930,1,0 days 00:00:00,2021-09-30 07:35:06.370,0 days 00:03:25.440000
24825,989.001039,84,2021-09-30 07:35:06.370,2021-09-30 07:35:06.370,1,0 days 00:00:00,NaT,NaT

Continuing for the dataframe - direction

In [7]:
direction["start_time"] = pd.to_datetime(direction["start_time"], errors="coerce")
direction["end_time"] = pd.to_datetime(direction["end_time"], errors="coerce")

def calculate_sequences(group):
    
    group["start_shift"] = group["start_time"].shift(-1)
    group["time_between_detection"] = group["start_shift"] - group["end_time"]
    return {
        
        "loc_code": group["loc_code"].tolist(),
        "time_between_detections": group["time_between_detection"].tolist(),
        "number_of_detections": group["number_of_detections"].tolist(),
        "dwell_time": group["dwell_time"].tolist()
    }

sequence_data = direction.groupby("tag_id").apply(calculate_sequences).reset_index(name="sequence_data")

print(sequence_data)

            tag_id                                      sequence_data
0         0.000061  {'loc_code': ['701'], 'time_between_detections...
1         0.000081  {'loc_code': ['701'], 'time_between_detections...
2         0.000174  {'loc_code': ['21'], 'time_between_detections'...
3         0.000183  {'loc_code': ['702'], 'time_between_detections...
4         3.237301  {'loc_code': ['11'], 'time_between_detections'...
...            ...                                                ...
109059  989.002028  {'loc_code': ['C1'], 'time_between_detections'...
109060  989.002028  {'loc_code': ['C2', 'C1'], 'time_between_detec...
109061  989.005135  {'loc_code': ['9C'], 'time_between_detections'...
109062  990.000004  {'loc_code': ['501'], 'time_between_detections...
109063  997.131499  {'loc_code': ['6B'], 'time_between_detections'...

[109064 rows x 2 columns]

In [8]:
sequence_df = pd.DataFrame(sequence_data)
sequence_df["loc_code"] = sequence_df['sequence_data'].apply(lambda x: x["loc_code"])
sequence_df["time_between_locations"] = sequence_df['sequence_data'].apply(lambda x: x["time_between_detections"])
sequence_df["number_of_detections"] = sequence_df['sequence_data'].apply(lambda x: x["number_of_detections"])
sequence_df["dwell_time"] = sequence_df['sequence_data'].apply(lambda x: x["dwell_time"])
sequence_df = sequence_df.drop(columns=['sequence_data'])

sequence_df

,tag_id,loc_code,time_between_locations,number_of_detections,dwell_time
0,0.000061,[701],[NaT],[1],[0 days 00:00:00]
1,0.000081,[701],[NaT],[1],[0 days 00:00:00]
2,0.000174,[21],[NaT],[1],[0 days 00:00:00]
3,0.000183,[702],[NaT],[1],[0 days 00:00:00]
4,3.237301,[11],[NaT],[1],[0 days 00:00:00]
...,...,...,...,...,...
109059,989.002028,[C1],[NaT],[4],[0 days 00:03:00.020000]
109060,989.002028,"[C2, C1]","[0 days 00:54:12.480000, NaT]","[4, 1]","[0 days 00:02:59.920000, 0 days 00:00:00]"
109061,989.005135,[9C],[NaT],[2],[0 days 00:00:00]
109062,990.000004,[501],[NaT],[4],[430 days 23:41:50.140000]
109063,997.131499,[6B],[NaT],[9],[0 days 00:49:16.240000]